repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-yaml
  - id: debug-statements
  - id: check-docstring-first
  - id: double-quote-string-fixer
  - id: fix-encoding-pragma
    args:
      - '--remove'
  - id: flake8
    args:
      - '--max-line-length=90'
