language: python

python:
  - "3.6"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
  - ./bootstrap.sh

script:
  - pre-commit run --all-files
  - pytest --cov newio
  # test install
  - cd $TRAVIS_BUILD_DIR
  - inv build
  - pip install --ignore-installed dist/*
  - cd /tmp && pytest $TRAVIS_BUILD_DIR/tests

after_success:
  - codecov
